### ISSUE TITLE
Error: missing dependancies

### ISSUE THREAD

**Issue by reswob10** [EbenKouao/pi-camera-stream-flask#1]
I'm trying to use the raspi minimal config to install.  Everything seems to work until I try to run the main.py from your git.  I get the following

root@raspberrypi:/opt# python3 ./pi-camera-stream-flask/main.py
Traceback (most recent call last):
  File "./pi-camera-stream-flask/main.py", line 7, in <module>
    from camera import VideoCamera
  File "/opt/pi-camera-stream-flask/camera.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

Do you know what dependencies it is looking for?

**Comment by reswob10** [comment]
So I got it running.  I had to install the following:

apt-get install python3-opencv
pip3 install picamera

**Comment by reswob10** [comment]
Also, in your make article at https://makezine.com/projects/beginner-project-a-remote-viewing-camera-with-raspberry-pi, you have typo.  You state the command to configure the pi is rasp-config, but it's raspi-config.  Nothing major

**Comment by EbenKouao** [comment]
Hi Reswob10, thanks for the shout. The changes should be made very soon. Cheers!

**Comment by funmi-cod** [comment]
Hello, I got this error 
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from camera import VideoCamera
ModuleNotFoundError: No module named 'camera'

what could be the issue?
